--Q1: 7-day rolling average of revenue per product

select P.PRODUCT_ID,P.PRODUCT_NAME,P.PRICE, D.REVENUE,
       AVG(D.REVENUE) OVER(PARTITION BY P.PRODUCT_ID
       ORDER BY D.SALE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS SEVEN_DAY_AVG
from SANDBOX.PLAYGROUND_02.PRODUCTS P
JOIN SANDBOX.PLAYGROUND_02.DAILY_SALES D ON P.PRODUCT_ID = D.PRODUCT_ID
ORDER BY P.PRODUCT_ID, D.SALE_DATE;;

--Q2: Top 3 Products By Revenue Per Category
WITH product_revenue AS (

    SELECT
        P.CATEGORY,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,

        SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE

    FROM SANDBOX.PLAYGROUND_02.PRODUCTS P

    JOIN SANDBOX.PLAYGROUND_02.ORDER_ITEMS OI
        ON P.PRODUCT_ID = OI.PRODUCT_ID

    GROUP BY
        P.CATEGORY,
        P.PRODUCT_ID,
        P.PRODUCT_NAME
),

ranked_products AS (

    SELECT *,
    
        DENSE_RANK() OVER(
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS RN

    FROM product_revenue
)

SELECT *
FROM ranked_products
WHERE RN <= 3
ORDER BY CATEGORY, RN;


--Q3 Find Salary Hike
WITH CTE AS(
SELECT E.EMPLOYEE_ID, E.NAME, D.DEPARTMENT_NAME, E.SALARY,
       LAG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_ID ORDER BY E.SALARY DESC) AS PREV_EMP_SAL
       FROM SANDBOX.PLAYGROUND_02.EMPLOYEES E
       LEFT JOIN SANDBOX.PLAYGROUND_02.DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
)
SELECT *, SALARY - PREV_EMP_SAL AS SALARY_DIFF
FROM CTE 
ORDER BY DEPARTMENT_NAME, SALARY DESC;