create database sandbox;
create schema playground;


CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.NATION AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.REGION AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.PARTSUPP AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.PART AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.SUPPLIER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.ORDERS AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

SELECT 
    'CREATE OR REPLACE TABLE SANDBOX.PLAYGROUND.' 
    || TABLE_NAME ||
    ' AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.' 
    || TABLE_NAME || ';'
FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'TPCH_SF1';

select 'SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.'||TABLE_NAME|| ';' FROM SANDBOX.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PLAYGROUND';

SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.PART;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.ORDERS;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.REGION;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.PARTSUPP;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.SUPPLIER;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.NATION;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.CUSTOMER;
SELECT TOP 100 * FROM SANDBOX.PLAYGROUND.LINEITEM;
---------------------------------------------------------
--q1: Customers with highest account balance in each nation

WITH ranked_customers AS (
    SELECT
        C.C_NAME,
        N.N_NAME,
        C.C_ACCTBAL,
        ROW_NUMBER() OVER(
            PARTITION BY N.N_NATIONKEY
            ORDER BY C.C_ACCTBAL DESC
        ) AS rn
    FROM CUSTOMER C
    JOIN NATION N
        ON C.C_NATIONKEY = N.N_NATIONKEY
)

SELECT C_NAME, N_NAME, C_ACCTBAL
FROM ranked_customers
WHERE rn = 1;
-- alternative correlated sub query
SELECT
    C.C_NAME,
    N.N_NAME,
    C.C_ACCTBAL
FROM CUSTOMER C
JOIN NATION N
    ON C.C_NATIONKEY = N.N_NATIONKEY
WHERE C.C_ACCTBAL = (
    SELECT MAX(C2.C_ACCTBAL)
    FROM CUSTOMER C2
    WHERE C2.C_NATIONKEY = C.C_NATIONKEY
);

--q2: Orders placed by customers from Germany
 SELECT C.C_NAME,O.O_ORDERKEY, O.O_ORDERDATE 
 FROM SANDBOX.PLAYGROUND.CUSTOMER C 
 JOIN SANDBOX.PLAYGROUND.ORDERS O ON O.O_CUSTKEY = C.C_CUSTKEY
 JOIN SANDBOX.PLAYGROUND.NATION N ON N.N_NATIONKEY = C.C_NATIONKEY
 WHERE N.N_NAME = 'GERMANY';

 --Q3 Find customers who never placed an order 
 SELECT C.C_CUSTKEY, C.C_NAME
 FROM SANDBOX.PLAYGROUND.CUSTOMER C 
 LEFT JOIN SANDBOX.PLAYGROUND.ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
 WHERE O.O_CUSTKEY IS NULL;

--ALTERNATIVE 
SELECT
    C.C_CUSTKEY,
    C.C_NAME
FROM CUSTOMER C
WHERE NOT EXISTS (
    SELECT 1
    FROM ORDERS O
    WHERE O.O_CUSTKEY = C.C_CUSTKEY
);

 --Q4: Find suppliers who supplied items whose extended price is greater than average extended price.
 SELECT S.S_NAME  FROM SANDBOX.PLAYGROUND.SUPPLIER S 
 JOIN SANDBOX.PLAYGROUND.LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
 WHERE L.L_EXTENDEDPRICE >
        (SELECT AVG(L.L_EXTENDEDPRICE) FROM SANDBOX.PLAYGROUND.LINEITEM L
 )
 GROUP BY S.S_NAME
;

--Q5: Find the latest order for each customer
WITH LATEST_ORD AS(
SELECT C.C_NAME, O.O_ORDERKEY, O.O_ORDERDATE, ROW_NUMBER() OVER(PARTITION BY O.O_CUSTKEY ORDER BY O.O_ORDERDATE DESC) AS RN 
FROM SANDBOX.PLAYGROUND.CUSTOMER C
JOIN SANDBOX.PLAYGROUND.ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
) 

SELECT C_NAME, O_ORDERKEY, O_ORDERDATE FROM LATEST_ORD 
WHERE RN = 1;
